services:
  # A Docker web service
  - type: web
    name: housing-dash
    env: python
    plan: free 
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir src app:server